// Department-specific content for PAC — used by content engine

export const departmentsContent: Record<string, { prefecture: string; specificite: string; nb_rge: number }> = {
    "01": { prefecture: "Bourg-en-Bresse", specificite: "Proximité de Lyon avec accès à un large réseau de techniciens PAC certifiés", nb_rge: 42 },
    "02": { prefecture: "Laon", specificite: "Fort taux de remplacement des chaudières fioul par des PAC en zone rurale", nb_rge: 28 },
    "03": { prefecture: "Moulins", specificite: "Parc immobilier ancien avec rénovation énergétique active vers les PAC", nb_rge: 22 },
    "04": { prefecture: "Digne-les-Bains", specificite: "Altitude nécessitant des PAC adaptées au froid avec entretien spécialisé", nb_rge: 18 },
    "05": { prefecture: "Gap", specificite: "Climat montagnard imposant des PAC haute température ou géothermiques", nb_rge: 15 },
    "06": { prefecture: "Nice", specificite: "Forte demande en PAC réversibles pour les villas et appartements du littoral", nb_rge: 65 },
    "07": { prefecture: "Privas", specificite: "Territoire rural en conversion progressive vers les pompes à chaleur", nb_rge: 24 },
    "08": { prefecture: "Charleville-Mézières", specificite: "Climat rigoureux nécessitant un entretien particulièrement soigneux avant l'hiver", nb_rge: 18 },
    "09": { prefecture: "Foix", specificite: "Mix PAC air/eau en plaine et géothermie dans les zones de piémont pyrénéen", nb_rge: 16 },
    "10": { prefecture: "Troyes", specificite: "Habitat pavillonnaire récent bien adapté aux PAC air/eau de moyenne puissance", nb_rge: 22 },
    "11": { prefecture: "Carcassonne", specificite: "Climat méditerranéen avec demande croissante en PAC réversibles", nb_rge: 28 },
    "12": { prefecture: "Rodez", specificite: "Plateaux et causses avec hivers froids nécessitant des PAC performantes", nb_rge: 20 },
    "13": { prefecture: "Marseille", specificite: "Premier département de la région pour le nombre de techniciens PAC certifiés RGE", nb_rge: 95 },
    "14": { prefecture: "Caen", specificite: "Climat doux normand offrant d'excellentes performances PAC toute l'année", nb_rge: 38 },
    "15": { prefecture: "Aurillac", specificite: "Altitude élevée imposant des PAC géothermiques pour des performances optimales", nb_rge: 12 },
    "16": { prefecture: "Angoulême", specificite: "Climat tempéré favorable aux PAC avec d'excellents rendements annuels", nb_rge: 26 },
    "17": { prefecture: "La Rochelle", specificite: "Littoral atlantique avec air salin nécessitant un traitement anti-corrosion spécifique", nb_rge: 32 },
    "18": { prefecture: "Bourges", specificite: "Programme actif de remplacement des chaudières fioul en zone rurale", nb_rge: 20 },
    "19": { prefecture: "Tulle", specificite: "Microclimats variés nécessitant un dimensionnement PAC adapté à chaque localisation", nb_rge: 18 },
    "2A": { prefecture: "Ajaccio", specificite: "Insularité majorant les coûts d'intervention et limitant les techniciens disponibles", nb_rge: 14 },
    "2B": { prefecture: "Bastia", specificite: "Marché insulaire avec surcoûts logistiques sur les pièces et fluides frigorigènes", nb_rge: 12 },
    "21": { prefecture: "Dijon", specificite: "Pôle de formation RGE avec bonne couverture en techniciens qualifiés", nb_rge: 32 },
    "22": { prefecture: "Saint-Brieuc", specificite: "Climat océanique doux garantissant un COP moyen parmi les meilleurs de France", nb_rge: 30 },
    "23": { prefecture: "Guéret", specificite: "Département rural avec peu de techniciens, anticipation des rendez-vous nécessaire", nb_rge: 10 },
    "24": { prefecture: "Périgueux", specificite: "Habitat ancien en pierre avec rénovation énergétique vers les PAC en forte croissance", nb_rge: 28 },
    "25": { prefecture: "Besançon", specificite: "Climat continental froid avec neige fréquente, PAC haute performance recommandées", nb_rge: 28 },
    "26": { prefecture: "Valence", specificite: "Zone de transition climatique avec PAC réversibles très demandées", nb_rge: 30 },
    "27": { prefecture: "Évreux", specificite: "Proximité francilienne avec habitat pavillonnaire dense et forte adoption PAC", nb_rge: 28 },
    "28": { prefecture: "Chartres", specificite: "Plaine de Beauce avec conversion fioul vers PAC bien avancée", nb_rge: 24 },
    "29": { prefecture: "Quimper", specificite: "Pointe bretonne avec embruns marins exigeant un entretien anti-corrosion renforcé", nb_rge: 35 },
    "30": { prefecture: "Nîmes", specificite: "Climat méditerranéen chaud avec PAC réversibles quasi systématiques dans le neuf", nb_rge: 35 },
    "31": { prefecture: "Toulouse", specificite: "Métropole dynamique avec forte demande en PAC pour habitat neuf et rénovation", nb_rge: 65 },
    "32": { prefecture: "Auch", specificite: "Département rural avec conversion progressive des systèmes de chauffage vers PAC", nb_rge: 14 },
    "33": { prefecture: "Bordeaux", specificite: "Métropole bordelaise avec fort taux d'équipement PAC dans les lotissements", nb_rge: 72 },
    "34": { prefecture: "Montpellier", specificite: "Litoral méditerranéen avec PAC réversibles dominantes pour chauffage et climatisation", nb_rge: 55 },
    "35": { prefecture: "Rennes", specificite: "Métropole rennaise avec politique volontariste sur les énergies renouvelables", nb_rge: 45 },
    "36": { prefecture: "Châteauroux", specificite: "Zone rurale avec remplacement actif des chaudières fioul par des PAC", nb_rge: 14 },
    "37": { prefecture: "Tours", specificite: "Val de Loire avec conditions climatiques idéales pour les PAC air/eau", nb_rge: 32 },
    "38": { prefecture: "Grenoble", specificite: "Vallées alpines avec mix PAC air/eau en plaine et géothermie en altitude", nb_rge: 55 },
    "39": { prefecture: "Lons-le-Saunier", specificite: "Jura avec gel prolongé, PAC performantes par grand froid indispensables", nb_rge: 18 },
    "40": { prefecture: "Mont-de-Marsan", specificite: "Climat océanique doux offrant d'excellentes performances PAC annuelles", nb_rge: 24 },
    "41": { prefecture: "Blois", specificite: "Val de Loire avec potentiel de conversion PAC important dans l'habitat ancien", nb_rge: 20 },
    "42": { prefecture: "Saint-Étienne", specificite: "Forte demande en PAC pour la rénovation du parc immobilier stéphanois", nb_rge: 35 },
    "43": { prefecture: "Le Puy-en-Velay", specificite: "Altitude élevée avec hivers longs, PAC géothermiques et haute température privilégiées", nb_rge: 14 },
    "44": { prefecture: "Nantes", specificite: "Métropole en forte croissance avec équipement PAC systématique dans le neuf", nb_rge: 58 },
    "45": { prefecture: "Orléans", specificite: "Couronne francilienne sud avec marché PAC dynamique en zone périurbaine", nb_rge: 30 },
    "46": { prefecture: "Cahors", specificite: "Causses et vallées avec habitat dispersé, PAC air/eau à climat tempéré", nb_rge: 12 },
    "47": { prefecture: "Agen", specificite: "Climat aquitain doux favorable aux PAC avec COP moyen supérieur à 3,5", nb_rge: 18 },
    "48": { prefecture: "Mende", specificite: "Département le moins peuplé, peu de techniciens et longs délais d'intervention", nb_rge: 8 },
    "49": { prefecture: "Angers", specificite: "Val de Loire avec climat doux idéal pour les PAC air/eau standard", nb_rge: 35 },
    "50": { prefecture: "Saint-Lô", specificite: "Climat océanique humide avec embruns, entretien anti-corrosion nécessaire en littoral", nb_rge: 24 },
    "51": { prefecture: "Châlons-en-Champagne", specificite: "Plaine champenoise avec hivers froids, PAC air/eau avec appoint recommandé", nb_rge: 28 },
    "52": { prefecture: "Chaumont", specificite: "Continental froid avec peu de techniciens, planifier l'entretien dès septembre", nb_rge: 12 },
    "53": { prefecture: "Laval", specificite: "Bocage mayennais avec habitat individuel dominant et PAC en forte progression", nb_rge: 16 },
    "54": { prefecture: "Nancy", specificite: "Bassin lorrain en reconversion énergétique avec remplacement du gaz par les PAC", nb_rge: 38 },
    "55": { prefecture: "Bar-le-Duc", specificite: "Département rural avec peu de techniciens certifiés, anticiper les rendez-vous", nb_rge: 10 },
    "56": { prefecture: "Vannes", specificite: "Littoral avec embruns salins nécessitant un entretien renforcé des PAC", nb_rge: 32 },
    "57": { prefecture: "Metz", specificite: "Bassin lorrain avec forte demande en PAC air/eau pour le parc existant", nb_rge: 42 },
    "58": { prefecture: "Nevers", specificite: "Morvan et campagnes avec remplacement progressif des chaudières par des PAC", nb_rge: 12 },
    "59": { prefecture: "Lille", specificite: "Métropole lilloise avec forte densité de techniciens et prix compétitifs", nb_rge: 85 },
    "60": { prefecture: "Beauvais", specificite: "Couronne francilienne nord avec habitat pavillonnaire dense et marché PAC actif", nb_rge: 35 },
    "61": { prefecture: "Alençon", specificite: "Bocage normand avec habitat ancien en conversion vers les PAC air/eau", nb_rge: 16 },
    "62": { prefecture: "Arras", specificite: "Côte d'Opale avec air marin nécessitant un entretien anti-corrosion spécifique", nb_rge: 52 },
    "63": { prefecture: "Clermont-Ferrand", specificite: "Mix altitude et plaine nécessitant des PAC adaptées à chaque localisation", nb_rge: 35 },
    "64": { prefecture: "Pau", specificite: "Pays basque et Béarn avec climat océanique doux favorable aux PAC haute performance", nb_rge: 35 },
    "65": { prefecture: "Tarbes", specificite: "Zone de piémont pyrénéen avec choix PAC géothermique recommandé en altitude", nb_rge: 16 },
    "66": { prefecture: "Perpignan", specificite: "Climat méditerranéen chaud avec PAC réversibles très demandées", nb_rge: 28 },
    "67": { prefecture: "Strasbourg", specificite: "Plaine d'Alsace avec climat continental et forte demande en PAC performantes", nb_rge: 48 },
    "68": { prefecture: "Colmar", specificite: "Vallée du Rhin et Vosges avec PAC à adapter selon altitude et exposition", nb_rge: 35 },
    "69": { prefecture: "Lyon", specificite: "Métropole avec forte concurrence entre techniciens garantissant des prix compétitifs", nb_rge: 82 },
    "70": { prefecture: "Vesoul", specificite: "Département rural avec peu de techniciens, anticiper les prises de rendez-vous", nb_rge: 14 },
    "71": { prefecture: "Mâcon", specificite: "Bresse et Mâconnais avec climat tempéré bien adapté aux PAC standard", nb_rge: 28 },
    "72": { prefecture: "Le Mans", specificite: "Habitat pavillonnaire avec forte adoption des PAC air/eau en neuf et rénovation", nb_rge: 28 },
    "73": { prefecture: "Chambéry", specificite: "Savoie alpine avec PAC géothermiques et haute température pour l'altitude", nb_rge: 30 },
    "74": { prefecture: "Annecy", specificite: "Marché PAC premium avec entretien spécialisé montagne et stations alpines", nb_rge: 38 },
    "75": { prefecture: "Paris", specificite: "Marché le plus concurrentiel de France avec forte demande en PAC air/air", nb_rge: 120 },
    "76": { prefecture: "Rouen", specificite: "Climat océanique doux avec air salin en littoral nécessitant un entretien adapté", nb_rge: 42 },
    "77": { prefecture: "Melun", specificite: "Grande couronne francilienne avec lotissements équipés en PAC air/eau", nb_rge: 52 },
    "78": { prefecture: "Versailles", specificite: "Habitat pavillonnaire haut de gamme avec PAC premium et géothermie", nb_rge: 58 },
    "79": { prefecture: "Niort", specificite: "Marais poitevin et plaines avec climat doux et excellent rendement PAC", nb_rge: 18 },
    "80": { prefecture: "Amiens", specificite: "Climat frais avec demande croissante en PAC air/eau performantes", nb_rge: 28 },
    "81": { prefecture: "Albi", specificite: "Climat tempéré tarnais avec bon potentiel PAC air/eau année round", nb_rge: 22 },
    "82": { prefecture: "Montauban", specificite: "Plaines du Sud-Ouest avec climat doux idéal pour les PAC air/eau", nb_rge: 16 },
    "83": { prefecture: "Toulon", specificite: "Littoral varois avec PAC réversibles dominantes et forte utilisation estivale", nb_rge: 52 },
    "84": { prefecture: "Avignon", specificite: "Climat sec et chaud avec PAC réversibles très demandées toute l'année", nb_rge: 32 },
    "85": { prefecture: "La Roche-sur-Yon", specificite: "Construction neuve dynamique avec PAC standard très répandues", nb_rge: 32 },
    "86": { prefecture: "Poitiers", specificite: "Climat tempéré avec conditions idéales pour les PAC air/eau standard", nb_rge: 22 },
    "87": { prefecture: "Limoges", specificite: "Plateaux limousins avec climat semi-océanique favorable aux PAC", nb_rge: 22 },
    "88": { prefecture: "Épinal", specificite: "Massif vosgien avec altitude variable, PAC adaptées au froid et à l'humidité", nb_rge: 20 },
    "89": { prefecture: "Auxerre", specificite: "Zone de transition climatique avec bon potentiel PAC air/eau", nb_rge: 18 },
    "90": { prefecture: "Belfort", specificite: "Petit département industriel avec habitat ouvrier en reconversion énergétique PAC", nb_rge: 10 },
    "91": { prefecture: "Évry", specificite: "Grande couronne sud avec lotissements pavillonnaires et forte demande PAC", nb_rge: 52 },
    "92": { prefecture: "Nanterre", specificite: "Petite couronne premium avec PAC air/air en copropriété et air/eau en pavillon", nb_rge: 65 },
    "93": { prefecture: "Bobigny", specificite: "Rénovation urbaine massive avec PAC dans les programmes neufs et réhabilitations", nb_rge: 45 },
    "94": { prefecture: "Créteil", specificite: "Marché mixte PAC air/air et air/eau en habitat dense de petite couronne", nb_rge: 48 },
    "95": { prefecture: "Cergy", specificite: "Grande couronne nord avec pavillonnaire récent et PAC air/eau très répandues", nb_rge: 45 }
};
